services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PUBLIC_API_URL=https://4057-34-169-149-75.ngrok-free.app/generate # Update later
      - ALLOWED_ORIGINS=http://localhost:3000,https://*.ngrok-free.app,https://a0ad-110-93-234-12.ngrok-free.app
      - DB_PATH=/app/healthsync.db
    volumes:
      - db_data:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
